In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn

In [2]:
bbc_text = pd.read_csv('news.csv')
bbc_text

Date                                                News  \
0    25-09-2023  Rajkummar Rao discusses the power of storytell...   
1    25-09-2023  I DON’T WANT TO BE NAIVE, BOX OFFICE SIGNIFIES...   
2    25-09-2023  Raghav, Parineeti opt for a subtle yet classy ...   
3    25-09-2023    Modi flags off 9 Vande Bharats across 11 states   
4    25-09-2023       India bag three silvers on Day 1 at Hangzhou   
..          ...                                                ...   
430  24-11-2023  3. Uttarkashi tunnel collapse LIVE updates | P...   
431  24-11-2023  4. “It’s For Country To Decide…”: S Jaishankar...   
432  24-11-2023  5. Minister urges Bihar CM to ban halal-certif...   
433  24-11-2023  6. LeT sniper trained on Pak-Afghan front kill...   
434  24-11-2023  7. Marriage Equality Petitioners Seek Open Cou...   

         Category        Newspaper  
0    Entertaiment  Hindustan Times  
1    Entertaiment  Hindustan Times  
2    Entertaiment  Hindustan Times  
3       Political  Hindustan Times  
4          Sports  Hindustan Times  
..            ...              ...  
430         India       News Today  
431         India       News Today  
432         India       News Today  
433         India       News Today  
434         India       News Today  

[435 rows x 4 columns]

In [3]:
bbc_text.Category.unique()

array(['Entertaiment', 'Political', 'Sports', 'Education', 'Enviroment',
       'Crime', 'India', 'Health', 'Business', 'World', 'Lifestyle',
       'Technology', 'State'], dtype=object)

In [4]:
bbc_text.Category = bbc_text.Category.map({'Entertaiment':0, 'Political':1, 'Sports':2, 'Education':3, 'Enviroment':4,'Crime':5,'India':6,'Health':7,'Business':8,'World':9,'Lifestyle':10,'Technology':11,'State':12})
bbc_text.Category.unique()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [5]:
bbc_text.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 435 entries, 0 to 434
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype 
---  ------     --------------  ----- 
 0   Date       435 non-null    object
 1   News       435 non-null    object
 2   Category   435 non-null    int64 
 3   Newspaper  435 non-null    object
dtypes: int64(1), object(3)
memory usage: 13.7+ KB


In [6]:
bbc_text.shape

(435, 4)

In [7]:
# bbc_news = bbc_text.values

X = bbc_text.News
y = bbc_text.Category

#split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, train_size = 0.7, random_state = 1)
print(X_train)
print(y_train)

303    1.      From October 11, Delhi HC to stream pr...
324    ·        Uttarkashi Tunnel Collapse: Kin Talk ...
347    India’s Defence Minister Rajnath Singh will pa...
314    10.  Iraqi PM to visit Moscow on October 10-11...
127    Israel says it’s ‘at war’ as terror attack kil...
                             ...                        
255                    AI belongs to the capitalists now
72     1,600 TICKETLESS TRAVELLERS CAUGHT AT DADAR ST...
396    Jaishankar ‘waiting for a thank you’ as India ...
235    China says surge in respiratory illnesses is c...
37     Speaker restores services of Delhi assembly fe...
Name: News, Length: 304, dtype: object
303     2
324    12
347     1
314     1
127     1
       ..
255    11
72      5
396    12
235     9
37      1
Name: Category, Length: 304, dtype: int64


In [8]:
# countVectorizer

from sklearn.feature_extraction.text import CountVectorizer
vec = CountVectorizer(stop_words = 'english')

In [9]:
# Assuming you have imported the necessary vectorizer
from sklearn.feature_extraction.text import CountVectorizer

# Instantiate the vectorizer
vec = CountVectorizer()

# Fit the vectorizer on the training data
vec.fit(X_train)

# Print the number of features (vocabulary size)
print(len(vec.get_feature_names_out()))

# Print the vocabulary dictionary
print(vec.vocabulary_)

1897
{'from': 686, 'october': 1183, '11': 2, 'delhi': 479, 'hc': 778, 'to': 1714, 'stream': 1611, 'proceedings': 1321, 'by': 295, 'cj': 367, 'live': 1013, 'uttarkashi': 1788, 'tunnel': 1755, 'collapse': 384, 'kin': 947, 'talk': 1655, 'trapped': 1739, 'workers': 1870, 'as': 151, 'govt': 731, 'executes': 599, 'new': 1159, 'rescue': 1407, 'plan': 1277, 'india': 851, 'defence': 476, 'minister': 1090, 'rajnath': 1360, 'singh': 1535, 'will': 1855, 'participate': 1240, 'in': 850, 'the': 1687, '10th': 1, 'asean': 152, 'ministers': 1091, 'meeting': 1073, 'plus': 1285, 'jakarta': 892, '10': 0, 'iraqi': 876, 'pm': 1286, 'visit': 1807, 'moscow': 1112, 'on': 1195, 'meet': 1072, 'putin': 1335, 'sources': 1562, 'israel': 882, 'says': 1466, 'it': 886, 'at': 167, 'war': 1824, 'terror': 1680, 'attack': 171, 'kills': 946, 'dozens': 545, 'west': 1844, 'lights': 1004, 'camera': 303, 'back': 191, 'action': 72, 'us': 1785, 'senate': 1494, 'votes': 1814, 'avert': 181, 'shutdown': 1530, 'leaves': 987, 'out': 1

In [10]:
# another way of representing the features
X_transformed = vec.transform(X_train)
X_transformed

<304x1897 sparse matrix of type '<class 'numpy.int64'>'
	with 3572 stored elements in Compressed Sparse Row format>

In [11]:
print(X_transformed)

  (0, 2)	1
  (0, 295)	1
  (0, 367)	1
  (0, 479)	1
  (0, 686)	1
  (0, 778)	1
  (0, 1013)	1
  (0, 1183)	1
  (0, 1321)	1
  (0, 1611)	1
  (0, 1714)	1
  (1, 151)	1
  (1, 384)	1
  (1, 599)	1
  (1, 731)	1
  (1, 947)	1
  (1, 1159)	1
  (1, 1277)	1
  (1, 1407)	1
  (1, 1655)	1
  (1, 1714)	1
  (1, 1739)	1
  (1, 1755)	1
  (1, 1788)	1
  (1, 1870)	1
  :	:
  (301, 1885)	1
  (302, 121)	1
  (302, 295)	1
  (302, 322)	1
  (302, 356)	1
  (302, 666)	1
  (302, 844)	1
  (302, 850)	1
  (302, 878)	1
  (302, 952)	1
  (302, 1214)	1
  (302, 1246)	1
  (302, 1409)	1
  (302, 1466)	1
  (302, 1634)	1
  (303, 83)	1
  (303, 162)	1
  (303, 479)	1
  (303, 632)	1
  (303, 778)	1
  (303, 1186)	1
  (303, 1210)	1
  (303, 1410)	1
  (303, 1500)	1
  (303, 1567)	1


In [12]:
print(X_transformed)

  (0, 2)	1
  (0, 295)	1
  (0, 367)	1
  (0, 479)	1
  (0, 686)	1
  (0, 778)	1
  (0, 1013)	1
  (0, 1183)	1
  (0, 1321)	1
  (0, 1611)	1
  (0, 1714)	1
  (1, 151)	1
  (1, 384)	1
  (1, 599)	1
  (1, 731)	1
  (1, 947)	1
  (1, 1159)	1
  (1, 1277)	1
  (1, 1407)	1
  (1, 1655)	1
  (1, 1714)	1
  (1, 1739)	1
  (1, 1755)	1
  (1, 1788)	1
  (1, 1870)	1
  :	:
  (301, 1885)	1
  (302, 121)	1
  (302, 295)	1
  (302, 322)	1
  (302, 356)	1
  (302, 666)	1
  (302, 844)	1
  (302, 850)	1
  (302, 878)	1
  (302, 952)	1
  (302, 1214)	1
  (302, 1246)	1
  (302, 1409)	1
  (302, 1466)	1
  (302, 1634)	1
  (303, 83)	1
  (303, 162)	1
  (303, 479)	1
  (303, 632)	1
  (303, 778)	1
  (303, 1186)	1
  (303, 1210)	1
  (303, 1410)	1
  (303, 1500)	1
  (303, 1567)	1


In [13]:
X_transformed.toarray()

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [14]:
print(X_transformed)

  (0, 2)	1
  (0, 295)	1
  (0, 367)	1
  (0, 479)	1
  (0, 686)	1
  (0, 778)	1
  (0, 1013)	1
  (0, 1183)	1
  (0, 1321)	1
  (0, 1611)	1
  (0, 1714)	1
  (1, 151)	1
  (1, 384)	1
  (1, 599)	1
  (1, 731)	1
  (1, 947)	1
  (1, 1159)	1
  (1, 1277)	1
  (1, 1407)	1
  (1, 1655)	1
  (1, 1714)	1
  (1, 1739)	1
  (1, 1755)	1
  (1, 1788)	1
  (1, 1870)	1
  :	:
  (301, 1885)	1
  (302, 121)	1
  (302, 295)	1
  (302, 322)	1
  (302, 356)	1
  (302, 666)	1
  (302, 844)	1
  (302, 850)	1
  (302, 878)	1
  (302, 952)	1
  (302, 1214)	1
  (302, 1246)	1
  (302, 1409)	1
  (302, 1466)	1
  (302, 1634)	1
  (303, 83)	1
  (303, 162)	1
  (303, 479)	1
  (303, 632)	1
  (303, 778)	1
  (303, 1186)	1
  (303, 1210)	1
  (303, 1410)	1
  (303, 1500)	1
  (303, 1567)	1


In [15]:
# for test data
X_test_transformed = vec.transform(X_test)
X_test_transformed

<131x1897 sparse matrix of type '<class 'numpy.int64'>'
	with 959 stored elements in Compressed Sparse Row format>

In [16]:
print(X_test_transformed)

  (0, 102)	1
  (0, 212)	1
  (0, 672)	1
  (0, 851)	1
  (0, 1090)	1
  (0, 1167)	1
  (0, 1539)	1
  (0, 1540)	1
  (0, 1597)	1
  (0, 1686)	1
  (0, 1687)	1
  (0, 1855)	1
  (0, 1856)	2
  (1, 28)	1
  (1, 121)	1
  (1, 178)	1
  (1, 179)	1
  (1, 851)	1
  (1, 1013)	2
  (1, 1646)	1
  (1, 1714)	1
  (1, 1815)	2
  (1, 1831)	1
  (1, 1847)	1
  (1, 1848)	1
  :	:
  (129, 1466)	1
  (129, 1714)	1
  (130, 140)	1
  (130, 179)	1
  (130, 191)	1
  (130, 292)	1
  (130, 328)	1
  (130, 337)	1
  (130, 438)	1
  (130, 816)	1
  (130, 1170)	2
  (130, 1200)	1
  (130, 1208)	1
  (130, 1234)	1
  (130, 1329)	1
  (130, 1383)	1
  (130, 1415)	1
  (130, 1689)	1
  (130, 1714)	1
  (130, 1749)	1
  (130, 1841)	1
  (130, 1852)	1
  (130, 1858)	1
  (130, 1872)	1
  (130, 1882)	1


In [17]:
# Assuming you have imported the necessary libraries
from sklearn.feature_extraction.text import CountVectorizer
import pandas as pd

# Instantiate the vectorizer
vec = CountVectorizer()

# Fit and transform the vectorizer on the training data
X_train_transformed = vec.fit_transform(X_train)

# Convert X_train_transformed to a DataFrame for readability
pd.DataFrame(X_train_transformed.toarray(), columns=vec.get_feature_names_out())


10  10th  11  12  12th  13  132  13c  15  16  ...  your  youtuber  yr  \
0     0     0   1   0     0   0    0    0   0   0  ...     0         0   0   
1     0     0   0   0     0   0    0    0   0   0  ...     0         0   0   
2     0     1   0   0     0   0    0    0   0   0  ...     0         0   0   
3     2     0   1   0     0   0    0    0   0   0  ...     0         0   0   
4     0     0   0   0     0   0    0    0   0   0  ...     0         0   0   
..   ..   ...  ..  ..   ...  ..  ...  ...  ..  ..  ...   ...       ...  ..   
299   0     0   0   0     0   0    0    0   0   0  ...     0         0   0   
300   0     0   0   0     0   0    0    0   0   0  ...     0         0   0   
301   0     0   0   0     0   0    0    0   0   0  ...     0         0   0   
302   0     0   0   0     0   0    0    0   0   0  ...     0         0   0   
303   0     0   0   0     0   0    0    0   0   0  ...     0         0   0   

     zeal  zealand  zerodha  zeta  zone  zoom  zoya  
0       0        0        0     0     0     0     0  
1       0        0        0     0     0     0     0  
2       0        0        0     0     0     0     0  
3       0        0        0     0     0     0     0  
4       0        0        0     0     0     0     0  
..    ...      ...      ...   ...   ...   ...   ...  
299     0        0        0     0     0     0     0  
300     0        0        0     0     0     0     0  
301     0        0        0     0     0     0     0  
302     0        0        0     0     0     0     0  
303     0        0        0     0     0     0     0  

[304 rows x 1897 columns]

In [18]:
from sklearn.naive_bayes import MultinomialNB

nb = MultinomialNB()
nb.fit(X_transformed, y_train)

MultinomialNB()

In [19]:
# fit
nb.fit(X_transformed,y_train)

# predict class
y_pred_class = nb.predict(X_test_transformed)

# predict probabilities
y_pred_proba = nb.predict_proba(X_test_transformed)

In [20]:
# printing the overall accuracy
from sklearn import metrics
metrics.accuracy_score(y_test, y_pred_class)

0.4351145038167939

In [21]:
# confusion matrix
metrics.confusion_matrix(y_test, y_pred_class)
# help(metrics.confusion_matrix)

array([[10,  0,  4,  0,  0,  1,  0,  0,  0,  0,  0,  2],
       [ 0,  9,  2,  0,  0,  1,  0,  0,  0,  0,  0,  3],
       [ 3,  0, 16,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  0,  4,  0,  0,  0,  0,  0,  0,  0,  0,  1],
       [ 3,  2,  0,  0,  3,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  3,  4,  0,  1,  5,  0,  0,  0,  0,  0,  3],
       [ 0,  1,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  4,  3,  0,  0,  0,  0,  2,  0,  0,  0,  3],
       [ 0,  0,  4,  0,  0,  0,  0,  0,  3,  0,  0,  0],
       [ 5,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0],
       [ 1,  1,  2,  0,  0,  0,  0,  0,  0,  2,  2,  0],
       [ 2,  2,  2,  0,  0,  2,  0,  0,  0,  0,  0,  6]], dtype=int64)

In [22]:
confusion = metrics.confusion_matrix(y_test, y_pred_class)
print(confusion)
TN = confusion[0, 0]
FP = confusion[0, 1]
FN = confusion[1, 0]
TP = confusion[1, 1]

[[10  0  4  0  0  1  0  0  0  0  0  2]
 [ 0  9  2  0  0  1  0  0  0  0  0  3]
 [ 3  0 16  0  0  0  0  0  0  0  0  0]
 [ 1  0  4  0  0  0  0  0  0  0  0  1]
 [ 3  2  0  0  3  0  0  0  0  0  0  0]
 [ 0  3  4  0  1  5  0  0  0  0  0  3]
 [ 0  1  1  0  0  0  0  0  0  0  0  0]
 [ 0  4  3  0  0  0  0  2  0  0  0  3]
 [ 0  0  4  0  0  0  0  0  3  0  0  0]
 [ 5  0  1  0  0  0  0  0  0  1  0  0]
 [ 1  1  2  0  0  0  0  0  0  2  2  0]
 [ 2  2  2  0  0  2  0  0  0  0  0  6]]


In [23]:
sensitivity = TP / float(FN + TP)
print("sensitivity",sensitivity)

specificity = TN / float(TN + FP)
print("specificity",specificity)

sensitivity 1.0
specificity 1.0


In [24]:
print("PRECISION SCORE :",metrics.precision_score(y_test, y_pred_class, average = 'micro'))
print("RECALL SCORE :", metrics.recall_score(y_test, y_pred_class, average = 'micro'))
print("F1 SCORE :",metrics.f1_score(y_test, y_pred_class, average = 'micro'))

PRECISION SCORE : 0.4351145038167939
RECALL SCORE : 0.4351145038167939
F1 SCORE : 0.4351145038167939


In [25]:
s1 = ['FIR against Delhi Minorities Commission chairman for inflammatory content on social media']
vec1 = vec.transform(s1).toarray()
print('Headline:' ,s1)
print(str(list(nb.predict(vec1))[0]).replace('0', 'Entertaiment').replace('1', 'Political').replace('2', 'Sports').replace('3','Education').replace('4','Enviroment').replace('5','Crime').replace('6','India').replace('7','Health').replace('8','Business').replace('9','World').replace('10','Lifestyle').replace('11','').replace('12','Technology').replace('13','State'))

Headline: ['FIR against Delhi Minorities Commission chairman for inflammatory content on social media']
Political


In [26]:
s1 = ['Amidst chaos,  Fernando Diniz sparkles hopes of a revolution with Selecao']
vec1 = vec.transform(s1).toarray()
print('Headline:' ,s1)
print(str(list(nb.predict(vec1))[0]).replace('0', 'Entertaiment').replace('1', 'Political').replace('2', 'Sports').replace('3','Education').replace('4','Enviroment').replace('5','Crime').replace('6','India').replace('7','Health').replace('8','Business').replace('9','World').replace('10','Lifestyle').replace('11','').replace('12','Technology').replace('13','State'))

Headline: ['Amidst chaos,  Fernando Diniz sparkles hopes of a revolution with Selecao']
Sports


In [27]:
s1 = ['IPL 2024: Shubman Gill named as Gujarat Titans captain after Hardik Pandya']
vec1 = vec.transform(s1).toarray()
print('Headline:' ,s1)
print(str(list(nb.predict(vec1))[0]).replace('0', 'Entertaiment').replace('1', 'Political').replace('2', 'Sports').replace('3','Education').replace('4','Enviroment').replace('5','Crime').replace('6','India').replace('7','Health').replace('8','Business').replace('9','World').replace('10','Lifestyle').replace('11','').replace('12','Technology').replace('13','State'))

Headline: ['IPL 2024: Shubman Gill named as Gujarat Titans captain after Hardik Pandya']
Sports


In [28]:
# Assuming you have your data (X) and labels (y)

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer  # or TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB  # or any other classifier
from sklearn.metrics import accuracy_score, classification_report

# Split the dataset into training, validation, and testing sets
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Instantiate a vectorizer (e.g., CountVectorizer or TfidfVectorizer)
vec = CountVectorizer()

# Fit and transform on the training data, and transform the validation and testing data
X_train_transformed = vec.fit_transform(X_train)
X_val_transformed = vec.transform(X_val)
X_test_transformed = vec.transform(X_test)

# Instantiate a classifier (e.g., Naive Bayes)
classifier = MultinomialNB()

# Train the classifier on the training data
classifier.fit(X_train_transformed, y_train)

# Validate the model on the validation set
y_val_pred = classifier.predict(X_val_transformed)

# Evaluate the model on the validation set
val_accuracy = accuracy_score(y_val, y_val_pred)
print(f"Validation Accuracy: {val_accuracy:.2f}")

# Test the model on the testing set
y_test_pred = classifier.predict(X_test_transformed)
# Evaluate the model on the testing set
test_accuracy = accuracy_score(y_test, y_test_pred)
print(f"Testing Accuracy: {test_accuracy:.2f}")

# Print classification report for more detailed evaluation metrics on the testing set
print("Classification Report:")
print(classification_report(y_test, y_test_pred))


Validation Accuracy: 0.49
Testing Accuracy: 0.39
Classification Report:
              precision    recall  f1-score   support

           0       0.40      0.50      0.44         8
           1       0.23      0.43      0.30         7
           2       0.38      1.00      0.55         8
           3       0.00      0.00      0.00         5
           5       0.00      0.00      0.00         4
           6       0.44      0.40      0.42        10
           7       0.00      0.00      0.00         1
           8       1.00      0.40      0.57         5
           9       0.50      0.50      0.50         2
          10       0.25      0.50      0.33         2
          11       0.00      0.00      0.00         2
          12       0.60      0.25      0.35        12

    accuracy                           0.39        66
   macro avg       0.32      0.33      0.29        66
weighted avg       0.39      0.39      0.35        66



C:\New folder\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\New folder\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\New folder\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
